export const SUBSCRIPTION_CREATE_REQUEST = "SUBSCRIPTION_CREATE_REQUEST";
export const SUBSCRIPTION_CREATE_SUCCESS = "SUBSCRIPTION_CREATE_SUCCESS";
export const SUBSCRIPTION_CREATE_FAIL = "SUBSCRIPTION_CREATE_FAIL";

export const SUBSCRIPTION_LIST_REQUEST = "SUBSCRIPTION_LIST_REQUEST";
export const SUBSCRIPTION_LIST_SUCCESS = "SUBSCRIPTION_LIST_SUCCESS";
export const SUBSCRIPTION_LIST_FAIL = "SUBSCRIPTION_LIST_FAIL";

export const SUBSCRIPTION_DELETE_REQUEST = "SUBSCRIPTION_DELETE_REQUEST";
export const SUBSCRIPTION_DELETE_SUCCESS = "SUBSCRIPTION_DELETE_SUCCESS";
export const SUBSCRIPTION_DELETE_FAIL = "SUBSCRIPTION_DELETE_FAIL";
export const SUBSCRIPTION_DELETE_RESET = "SUBSCRIPTION_DELETE_RESET";


export const SUBSCRIPTION_UPDATE_REQUEST = "SUBSCRIPTION_UPDATE_REQUEST";
export const SUBSCRIPTION_UPDATE_SUCCESS = "SUBSCRIPTION_UPDATE_SUCCESS";
export const SUBSCRIPTION_UPDATE_FAIL = "SUBSCRIPTION_UPDATE_FAIL";


